releaseType: java-yoshi
bumpMinorPreMajor: true
handleGHRelease: true
branches:
  - releaseType: java-lts
    bumpMinorPreMajor: true
    branch: 1.10.1-sp
    handleGHRelease: true
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-yoshi
    branch: java7
