rebaseMergeAllowed: true
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
  - pattern: main
    isAdminEnforced: true
    requiredStatusCheckContexts:
      - units
      - format
      - cla/google
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: true
  - pattern: 1.10.1-sp
    isAdminEnforced: true
    requiredStatusCheckContexts:
      - units
      - format
      - cla/google
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: true
  - pattern: java7
    isAdminEnforced: true
    requiredStatusCheckContexts:
      - units
      - format
      - cla/google
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: true
permissionRules:
  - team: Googlers
    permission: pull
  - team: yoshi-java
    permission: push
  - team: yoshi-java-admins
    permission: admin
  - team: yoshi-admins
    permission: admin
