sudo: false
dist: trusty
language: java
addons:
  # https://github.com/travis-ci/travis-ci/issues/5227#issuecomment-165131913
  hosts:
    - fake-hostname-to-work-around-travis-bug
  hostname: fake-hostname-to-work-around-travis-bug
jdk:
  - oraclejdk8
  - openjdk8
script:
  ./gradlew check --info
after_success:
  - bash <(curl -s https://codecov.io/bash)
