on:
  push:
    branches:
    - java7
  pull_request:
name: ci
jobs:
  units:
    runs-on: ubuntu-latest
    env:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - run: java -version
    - name: Gradle Assemble
      run: ./gradlew assemble
    - name: Gradle Test
      run: ./gradlew test
    - name: Gradle Build
      run: ./gradlew build install
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Java Linter
      run: ./gradlew googleJavaFormat