on:
  push:
    branches:
    - main
  pull_request:
name: ci
jobs:
  units:
    runs-on: ubuntu-latest
    steps:
      strategy:
        fail-fast: false
        matrix:
          java: [ 8, 11, 17 ]
      steps:
      - name: Get current week within the year
        id: date
        run: echo "::set-output name=week_of_year::$(date +'%W' --utc)"
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{matrix.java}}
      - run: java -version
      - uses: actions/cache@v3
        id: mvn-cache
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-unified-${{ steps.date.outputs.week_of_year }}
      - run: .kokoro/build.sh
        env:
          JOB_TYPE: test
          JOB_NAME: units-${{matrix.java}}
    lint:
      runs-on: ubuntu-latest
      steps:
        - name: Get current week within the year
          id: date
          run: echo "::set-output name=week_of_year::$(date +'%W' --utc)"
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            distribution: temurin
            java-version: 8
        - run: java -version
        - uses: actions/cache@v3
          id: mvn-cache
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-unified-${{ steps.date.outputs.week_of_year }}
        - run: java -version
        - run: mvn -B -ntp com.coveo:fmt-maven-plugin:check
        - run: mvn -B -ntp checkstyle:check@checkstyle
