on:
  push:
    branches:
    - main
  pull_request:
name: downstream
jobs:
  dependencies:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [17]
        repo:
        - memcache
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{matrix.java}}
    - run: java -version
    - run: sudo apt-get install libxml2-utils
    - run: .kokoro/downstream-client-library-check.sh ${{matrix.repo}}