on:
  push:
    branches:
    - main
  pull_request:
name: downstream
jobs:
  dependencies:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [8]
        repo:
        - eventarc
        - filestore
        - firestore
        - functions
        - game-servers
        - gke-connect-gateway
        - gkehub
        - gsuite-addons
        - iam-admin
        - iamcredentials
        - iot
        - kms
        - language
        - life-sciences
        - logging
        - logging-logback
        - managed-identities
        - mediatranslation
        - memcache
        - monitoring
        - monitoring-dashboards
        - network-management
        - network-security
        - networkconnectivity
        - notebooks
        - orchestration-airflow
        - orgpolicy
        - os-config
        - os-login
        - phishingprotection
        - policy-troubleshooter
        - private-catalog
        - profiler
        - pubsublite
        - recaptchaenterprise
        - recommendations-ai
        - recommender
        - redis
        - resource-settings
        - resourcemanager
        - retail
        - scheduler
        - secretmanager
        - security-private-ca
        - securitycenter
        - securitycenter-settings
        - service-control
        - service-management
        - service-usage
        - servicedirectory
        - shell
        - spanner
        - spanner-jdbc
        - speech
        - storage
        - storage-nio
        - storage-transfer
        - talent
        - tasks
        - texttospeech
        - tpu
        - trace
        - translate
        - video-intelligence
        - video-transcoder
        - vision
        - vpcaccess
        - webrisk
        - websecurityscanner
        - workflow-executions
        - workflows
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{matrix.java}}
    - run: java -version
    - run: sudo apt-get install libxml2-utils
    - run: .kokoro/downstream-client-library-check.sh ${{matrix.repo}}